import { motion } from 'motion/react';
import { Loader2, ThumbsDown, ThumbsUp, X } from 'lucide-react';
import type { NextGenUserRecord } from './nextGenActivities.types';
import type { UseNextGenQuestionsResult } from './useNextGenQuestions';

export default function NextGenPeerReviewPanel({ user, controller, isArabic, onClose }: { user: NextGenUserRecord; controller: UseNextGenQuestionsResult; isArabic: boolean; onClose: () => void }) {
  const { reviewableSessions, isLoadingPeerReview, peerReviewError, isSubmittingPeerVote, submittingVoteSessionId, handlePeerVote } = controller;
  return (
    <motion.section initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mt-8 bg-white rounded-[30px] border border-[rgba(139,30,30,0.10)] shadow-[0_18px_48px_rgba(0,0,0,0.08)] overflow-hidden">
      <div className="flex items-center justify-between gap-4 p-6 bg-[#8b1e1e] text-white"><div className="flex items-center gap-3"><ThumbsUp size={24} /><div><h2 className="text-2xl font-bold">{isArabic ? 'مراجعة الأسئلة' : 'Peer Review Questions'}</h2><p className="text-white/75 text-sm mt-1">{isArabic ? 'تُخفى الأسئلة التي سبق أن صوّت عليها معرّفك.' : 'Questions already voted on by your identifier are hidden.'}</p></div></div><button type="button" onClick={onClose} className="p-2 rounded-full hover:bg-white/10 transition-colors"><X size={22} /></button></div>
      <div className="p-6 md:p-8 space-y-6">
        <div className="rounded-2xl border border-amber-100 bg-amber-50 p-5 text-amber-900"><h3 className="font-bold mb-2">{isArabic ? 'التصويت مرتبط بالمعرّف' : 'Identifier-Based Voting'}</h3><p className="text-sm leading-relaxed">{isArabic ? `يمكن للمعرّف ${user.userId} التصويت مرة واحدة فقط على كل سؤال. يتم التحقق من ذلك داخل قاعدة البيانات، وليس فقط في هذه الجلسة.` : `ID ${user.userId} can vote only once on each question. This is enforced in the database, not only for the current browser session.`}</p></div>
        <div className="text-sm text-gray-500">{isArabic ? `الأسئلة المتاحة لهذا المعرّف: ${reviewableSessions.length}` : `Questions available for this identifier: ${reviewableSessions.length}`}</div>
        {peerReviewError && <div className="text-sm text-red-600 bg-red-50 border border-red-100 rounded-xl p-4">{peerReviewError}</div>}
        {isLoadingPeerReview && <div className="flex items-center gap-2 text-gray-500 bg-stone-50 border border-gray-100 rounded-2xl p-5"><Loader2 size={18} className="animate-spin" />{isArabic ? 'جار تحميل الأسئلة...' : 'Loading questions...'}</div>}
        {!isLoadingPeerReview && reviewableSessions.length === 0 && <div className="text-center bg-stone-50 border border-gray-100 rounded-3xl p-10"><div className="w-14 h-14 mx-auto grid place-items-center rounded-full bg-[#f8eeee] text-[#8b1e1e] mb-4"><ThumbsUp size={24} /></div><h3 className="text-xl font-bold text-[#8b1e1e] mb-2">{isArabic ? 'لا توجد أسئلة أخرى للمراجعة' : 'No More Questions to Review'}</h3><p className="text-gray-500">{isArabic ? 'صوّت هذا المعرّف بالفعل على كل الأسئلة المتاحة، أو لا توجد أسئلة بعد.' : 'This identifier has already voted on every available question, or no questions exist yet.'}</p></div>}
        {!isLoadingPeerReview && reviewableSessions.length > 0 && <div className="space-y-4">{reviewableSessions.map((session, index) => <motion.div key={session.firebaseId} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.035 }} className="rounded-[28px] bg-stone-50 border border-gray-100 p-6 space-y-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2 mb-3"><span className="px-3 py-1 bg-[#8b1e1e] text-white rounded-full text-xs font-bold">{isArabic ? `ترتيب #${index + 1}` : `Rank #${index + 1}`}</span><span className="px-3 py-1 bg-[#f8eeee] text-[#8b1e1e] rounded-full text-xs font-bold border border-[rgba(139,30,30,0.10)]">{session.category}</span></div><h3 className="text-2xl font-bold text-[#641414] leading-snug">{session.question}</h3><p className="text-xs text-gray-400 mt-3 font-bold uppercase tracking-widest">{isArabic ? 'أرقام التصويت مخفية أثناء مراجعة الزملاء' : 'Vote totals hidden during peer review'}</p></div>{session.notes && <div className="bg-white border border-gray-100 rounded-2xl p-4"><h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">{isArabic ? 'ملاحظات' : 'Notes'}</h4><p className="text-sm leading-relaxed text-[#333]">{session.notes}</p></div>}<div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2"><button type="button" onClick={() => handlePeerVote(session.firebaseId, 'upvote')} disabled={isSubmittingPeerVote} className="inline-flex items-center justify-center gap-2 px-6 py-4 bg-green-700 text-white rounded-2xl font-bold hover:bg-green-800 disabled:opacity-60 disabled:cursor-not-allowed transition-colors">{submittingVoteSessionId === session.firebaseId ? <Loader2 size={18} className="animate-spin" /> : <ThumbsUp size={18} />}{isArabic ? 'تصويت إيجابي' : 'Upvote'}</button><button type="button" onClick={() => handlePeerVote(session.firebaseId, 'downvote')} disabled={isSubmittingPeerVote} className="inline-flex items-center justify-center gap-2 px-6 py-4 bg-red-700 text-white rounded-2xl font-bold hover:bg-red-800 disabled:opacity-60 disabled:cursor-not-allowed transition-colors">{submittingVoteSessionId === session.firebaseId ? <Loader2 size={18} className="animate-spin" /> : <ThumbsDown size={18} />}{isArabic ? 'تصويت سلبي' : 'Downvote'}</button></div></motion.div>)}</div>}
      </div>
    </motion.section>
  );
}
